### ISSUE TITLE
error in spine

### ISSUE THREAD

**Issue by fmlove** [jefferis/nat#320]
```r
> da1=read.neuron.catmaid(57311)
> sda1=spine(da1)
Error in .Call("R_igraph_es_path", graph, as.igraph.vs(graph, path) -  : 
  At type_indexededgelist.c:1173 : Cannot get edge id, no such edge, Invalid value
```

**Comment by jefferis** [comment]
The error seems to come in the final `prune_edges` step: 

https://github.com/jefferis/nat/blob/2d0f5f89b1121f40b03a47b7c68da9df7b5b6c2a/R/ngraph.R#L257

It looks like we are calculating a vertex set with get.diameter but then pruning as if they constituted an edge set. If correct, not sure how that ever worked.

**Comment by jefferis** [comment]
ok, `prune_edges` is supposed to be able to understand vertex sequences, but seems to be failing here. Interestingly asking for the spine using the soma as a starting point works fine.

**Comment by jefferis** [comment]
The problem was with the handling of directed paths. When not using the neuron's start point, we were calling `get.diameter` to return the longest path without reference to the direction of edges. This implies that the longest graph for a linear neuron with an origin in the middle such as E1----<----O -->--E2 would be all the way from E1 to  E2. However the edge direction would reverse as the path crossed the origin. To deal with this we need to call `E(g, edges, directed=FALSE)` when the edge sequence is not guaranteed to be in the correct order. Since there should only ever be one edge between each pair of nodes, we can set `directed=FALSE` all the time.
